POST https://mayiuserms.herokuapp.com/api/register HTTP/1.1
content-type: application/json

{
    "username": "AbdoRayan123",
    "password": "qwertyyy23",
    "public_key": "dont have one right now"
}

####

POST http://localhost:3000/api/login HTTP/1.1
content-type: application/json

{
    "address": "0x1d44",
    "password": "qwertyyy"
}

####

PUT http://localhost:3000/api/user/settings HTTP/1.1
content-type: application/json

{
    "address": "0x1d44",
    "password": "qwertyyy",
    "update": {}
}

####

POST https://mayiuserms.herokuapp.com/api/user/messages HTTP/1.1
content-type: application/json

{
    "address":"0x1d44",
    "password":"qwertyyy"
}

####

GET https://mayiuserms.herokuapp.com/api/record/0x2a17 HTTP/1.1